import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import BottomNav from "../components/BottomNav";
import RegisterSW from "../components/RegisterSW";
import StartupMigration from "../components/StartupMigration";
import TopBar from "../components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        {/* PWA manifest + theme color */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
        {/* iOS PWA support */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="HydraIQ" />
        <link rel="apple-touch-icon" href="/icons/icon-192.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RegisterSW />
        <StartupMigration />

        {/* TopBar likely uses useSearchParams via DateSwitcher — must be wrapped in Suspense */}
        <Suspense fallback={null}>
          <TopBar />
        </Suspense>

        <div className="mx-auto flex min-h-screen max-w-[420px] flex-col text-zinc-900 dark:text-zinc-100 pt-14">
          <main className="flex-1 overflow-x-hidden pb-[88px] px-4">{children}</main>
        </div>

        <BottomNav />
      </body>
    </html>
  );
}
