import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "../components/BottomNav";
import RegisterSW from "../components/RegisterSW";
import StartupMigration from "../components/StartupMigration";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RegisterSW />
        <StartupMigration />
        <div className="mx-auto flex min-h-screen max-w-[420px] flex-col bg-white text-zinc-900 dark:bg-black dark:text-zinc-100">
          <main className="flex-1 overflow-x-hidden pb-[88px]">
            {children}
          </main>
        </div>
        <BottomNav />
      </body>
    </html>
  );
}

